config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :medical_records do
    collection do
      get 'partials/:record_type', to: 'medical_records#load_partial', as: 'load_partial'
      get 'fields_partials/:record_type', to: 'medical_records#fields_partial', as: 'fields_partial'
    end
  end

  resources :approvals

  resources :posts do
    member do
      put 'approve'
      put 'disapprove'
    end
    resources :comments, only: %i[create new show update destroy] do
      member do
        get 'edit'
        put 'approve'
        put 'disapprove'
      end
    end
  end

  resources :clans do
    resources :clan_memberships, only: %i[create destroy index show]
    member do
      get 'show_members'
      patch 'toggle_trust/:user_id', to: 'clans#toggle_trust', as: 'toggle_trust'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/models/comment.rb
# frozen_string_literal: true

# app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                      :uuid             not null, primary key
#  body                    :text
#  post_id                 :uuid             not null
#  author_id               :uuid             not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  parent_id               :uuid
#  replies_count           :integer          default(0), not null
#  cached_votes_total      :integer          default(0), not null
#  cached_votes_score      :integer          default(0), not null
#  cached_votes_up         :integer          default(0), not null
#  cached_votes_down       :integer          default(0), not null
#  cached_weighted_score   :integer          default(0), not null
#  cached_weighted_total   :integer          default(0), not null
#  cached_weighted_average :float            default(0.0), not null
#  cached_vote_diff        :integer          default(0)
#  votes_count             :integer          default(0), not null
#
class Comment < ApplicationRecord
  include Votable
  include Ransackable

  # Associations
  belongs_to :post, counter_cache: :comments_count
  belongs_to :author, class_name: 'User'
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  # Counter cache for vote counts
  counter_culture :post, column_name: 'cached_votes_total'
  counter_culture :post, column_name: 'cached_votes_up', delta_column: 'cached_votes_up'
  counter_culture :post, column_name: 'cached_votes_down', delta_column: 'cached_votes_down'
  counter_culture :post, column_name: 'cached_vote_diff', delta_column: 'cached_vote_diff'

  # Counter cache for replies count
  counter_culture :parent, column_name: 'replies_count'

  after_create_commit :enqueue_notification_job

  # Instance methods
  def depth
    parent ? 1 + parent.depth : 0
  end

  private

  def enqueue_notification_job
    NewCommentNotificationJob.perform_later(self)
  end
end

# Reset counter cache for replies_count
Comment.counter_culture_fix_counts column_name: 'replies_count'

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  include PostFindable
  before_action :find_post, except: %i[show edit update destroy approve disapprove]
  before_action :set_post, except: %i[show edit update destroy approve disapprove]
  before_action :set_comment, only: %i[show edit update destroy approve disapprove]
  before_action :find_parent_comment, only: %i[create new]
  before_action :build_comment, only: %i[create new edit update]
  before_action :authorize_comment, only: %i[index show update approve disapprove]

  # GET /comments or /comments.json
  def index
    @comments = policy_scope(Comment)
  end

  # GET /comments/1 or /comments/1.json
  def show; end

  # GET /comments/new
  def new
    find_parent_comment
    @comment = @post.comments.build(parent_id: params[:parent_id])
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    find_parent_comment
    @post = @parent_comment.post if @parent_comment.present?
    @comment = @post.comments.build(comment_params.merge(author: current_user))
    authorize @comment

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      flash.now[:alert] = 'Failed to create comment. You may not have permission to comment.'
      render 'posts/show', status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @post = Post.find(params[:post_id])
    respond_to do |format|
      if @comment.update(comment_params)
        redirect_to post_path(@comment.post), notice: 'Comment was successfully updated.'
        format.json { render :show, status: :ok, location: @comment }
      else
        render :edit
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(@comment.post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @comment.liked_by current_user
    redirect_to post_path(@comment.post), notice: 'Comment approved!'
  end

  def disapprove
    @comment.disliked_by current_user
    redirect_to post_path(@comment.post), notice: 'Comment disapproved!'
  end

  private

  def set_post
    if params[:post_id]
      @post = Post.find(params[:post_id])
    elsif params[:comment_id]
      # 'comment_id' is the parent comment's ID when replying
      parent_comment = Comment.find(params[:comment_id])
      @post = parent_comment.post
    else
      redirect_to root_url, alert: 'Post not found.'
    end
  end

  def find_parent_comment
    @parent_comment = Comment.find_by(id: params[:parent_id]) if params[:parent_id].present?
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def build_comment
    @comment = @post.comments.build(comment_params.merge(author: current_user)) if @post.present?
    @comment.parent = @parent_comment if @parent_comment.present?
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def authorize_comment
    authorize @comment
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- views/comments/_comment.html.erb -->
<style>
  /* Base styles for all cards */
    .timeline-item {
      border: 1px solid #ccc; /* Adds a subtle border to the card */
      margin-bottom: 10px; /* Spacing between cards */
      padding: 15px; 
      border-radius: 5px; 
    }

    /* Background color for parent comment */
    .timeline-item:not(.nested-comments .timeline-item) {
      background-color: #f3f4f6; /* Same color as the stats section */
    }

    /* Alternating background colors for nested comments */
    .nested-comments .timeline-item {
      border-left: 2px solid #ccc;
      padding-left: 30px; 
      margin-left: 20px; 
    }

    .nested-comments .timeline-item {
      background-color: #f5f5f5; 
    }

    .nested-comments .nested-comments .timeline-item {
      background-color: #f3f4f6; /* Same color as the parent comment */
    }

    .nested-comments .nested-comments .nested-comments .timeline-item {
      background-color: #f5f5f5; /* Same color as the first level of nested comments */
    }
</style>
<!-- Ensure that each nested comment is wrapped with the appropriate classes -->
<div class="timeline-item card card-body">
  <div class="flex items-start gap-4">
    <div class="avatar">
      <div class="w-10 h-10 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
        <% if comment.author.profile_picture.present? %>
          <%= image_tag comment.author.profile_picture, alt: "#{comment.author.name}'s profile picture", class: "rounded-full" %>
        <% else %>
          <%= image_tag "default_profile_picture.png", alt: "Default profile picture", class: "rounded-full" %>
        <% end %>
      </div>
    </div>
    <div class="flex-grow">
      <div class="flex justify-between items-center">
        <h4 class="font-bold"><%= comment.author.name %></h4>
        <div class="text-sm font-semibold <%= 'text-primary' if comment.approval_rating > 70 %> <%= 'text-accent' if comment.approval_rating < 50 %> <%= 'text-yellow-500' if comment.approval_rating >= 50 && comment.approval_rating <= 70 %>"><%= comment.approval_rating %>%</div>
      </div>
      <time class="font-mono italic text-sm"><%= time_ago_in_words(comment.created_at) %> ago</time>
      <p><%= comment.body %></p>
    </div>
  </div>
  <!-- Comment Actions -->
  <div class="flex justify-between items-center mt-2">
    <!-- Vote Buttons -->
    <div class="flex space-x-2">
      <% if policy(comment).approve? %>
        <%= button_to approve_post_comment_path(comment.post, comment), method: :put, class: "btn btn-primary btn-xs" do %>
          <i class="fa-solid fa-arrow-up" style="color: #ffffff;"></i>
        <% end %>
      <% end %>
      <% if policy(comment).disapprove? %>
        <%= button_to disapprove_post_comment_path(comment.post, comment), method: :put, class: "btn btn-accent btn-xs" do %>
          <i class="fa-solid fa-arrow-down" style="color: #ffffff;"></i>
        <% end %>
      <% end %>
    </div>
    <!-- Edit and Delete Buttons -->
    <div class="flex space-x-2">
      <div>
        <!-- Reply Button -->
        <% if policy(Comment.new(post: @post, parent: comment)).create? %>
          <label for="reply-modal-<%= comment.id %>" class="btn btn-xs btn-secondary cursor-pointer">
            <i class="fa-solid fa-reply"></i> Reply
          </label>
        <% end %>
      </div>
      <% if policy(comment).update? %>
        <label for="edit-modal-<%= comment.id %>" class="btn btn-solid btn-accent btn-xs cursor-pointer">
          <i class="fa-solid fa-pencil" style="color: #ffffff;"></i>
        </label>
      <% end %>
      <% if policy(comment).destroy? %>
        <label for="delete-modal-<%= comment.id %>" class="btn btn-solid btn-accent btn-xs">
          <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
        </label>
      <% end %>
      <!-- Confirmation Modal -->
      <input type="checkbox" id="delete-modal-<%= comment.id %>" class="modal-toggle" />
      <div class="modal">
        <div class="modal-box">
          <h3 class="font-bold text-lg">Delete Comment</h3>
          <p class="py-4">Are you sure you want to delete this comment?</p>
          <div class="modal-action flex justify-between">
            <div class="flex-1">
              <%= button_to "Yes, delete it", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-error btn-block" %>
            </div>
            <div class="flex-1 ml-4">
              <label for="delete-modal-<%= comment.id %>" class="btn btn-block">Cancel</label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal for editing comment -->
  <input type="checkbox" id="edit-modal-<%= comment.id %>" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="text-lg font-bold">Edit Comment</h3>
      <%= render partial: 'comments/form', locals: { post: comment.post, comment: comment } %>
      <label for="edit-modal-<%= comment.id %>" class="btn btn-outline btn-accent">Close</label>
    </div>
    <label for="edit-modal-<%= comment.id %>" class="modal-backdrop cursor-pointer"></label>
  </div>
  <!-- Modal for reply -->
  <input type="checkbox" id="reply-modal-<%= comment.id %>" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="text-lg font-bold">Reply to <%= comment.author.name %></h3>
      <%= render partial: 'comments/form', locals: { post: comment.post, comment: Comment.new(parent_id: comment.id) } %>
      <label for="reply-modal-<%= comment.id %>" class="btn btn-outline btn-accent">Close</label>
    </div>
    <label for="reply-modal-<%= comment.id %>" class="modal-backdrop cursor-pointer"></label>
  </div>
  <!-- Nested Comments -->
  <% if comment.replies.any? %>
    <div class="nested-comments ml-10 mt-4">
      <% comment.replies.each do |child_comment| %>
        <%= render 'comments/comment', comment: child_comment %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<!-- views/comments/_form.html.erb -->
<% if policy(comment).create? || policy(comment).update? %>
  <% if comment.new_record? %>
    <%= form_with(model: [post, comment], url: post_comments_path(post), local: true) do |form| %>
      <% if comment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
          <ul>
            <% comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
        <% placeholder_text = comment.parent_id.present? ? "Write a reply..." : "Add a comment..." %>
        <%= form.text_area :body, class: "textarea textarea-primary w-full", placeholder: placeholder_text %>
      </div>
      <%= form.hidden_field :author_id, value: current_user.id %>
      <%= form.hidden_field :parent_id, value: comment.parent_id %>
      <div class="flex justify-end mt-2">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% else %>
    <%= form_with(model: [comment.post, comment], local: true) do |form| %>
      <% if comment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
          <ul>
            <% comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
        <%= form.text_area :body, class: "textarea textarea-primary w-full", placeholder: "Edit your comment..." %>
      </div>
      <%= form.hidden_field :author_id, value: current_user.id %>
      <%= form.hidden_field :parent_id %>
      <div class="flex justify-end mt-2">
        <%= form.submit "Update Comment", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>You are not authorized to <%= comment.new_record? ? 'create' : 'update' %> this comment.</p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<!-- views/comments/index -->
<h1>Comments</h1>
<% @comments.each do |comment| %>
  <%= render comment %>
  <p>
    <%= link_to "Show this comment", comment %>
  </p>
<% end %>
<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<!-- views/comments/new.html.erb -->
<h1>New comment</h1>

<%= render "form", comment: @comment %>
<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<!-- views/comments/show.html.erb -->
<%= render @comment %>