config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :medical_records do
    collection do
      get 'partials/:record_type', to: 'medical_records#load_partial', as: 'load_partial'
      get 'fields_partials/:record_type', to: 'medical_records#fields_partial', as: 'fields_partial'
    end
  end

  resources :approvals

  resources :posts do
    member do
      put 'approve'
      put 'disapprove'
    end
    resources :comments, only: %i[create new show update destroy] do
      member do
        get 'edit'
        put 'approve'
        put 'disapprove'
      end
    end
  end

  resources :clans do
    resources :clan_memberships, only: %i[create destroy index show]
    member do
      get 'show_members'
      patch 'toggle_trust/:user_id', to: 'clans#toggle_trust', as: 'toggle_trust'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id                      :uuid             not null, primary key
#  author_id               :uuid
#  body                    :text
#  image                   :string
#  trusted                 :boolean
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  approvals_count         :integer          default(0), not null
#  medical_record_id       :uuid
#  cached_votes_total      :integer          default(0)
#  cached_votes_score      :integer          default(0)
#  cached_votes_up         :integer          default(0)
#  cached_votes_down       :integer          default(0)
#  cached_weighted_score   :integer          default(0)
#  cached_weighted_total   :integer          default(0)
#  cached_weighted_average :float            default(0.0)
#  title                   :string
#  cached_vote_diff        :integer          default(0)
#  comments_count          :integer          default(0), not null
#
class Post < ApplicationRecord
  include Votable
  include Ransackable
  has_one_attached :image
  belongs_to :author, class_name: 'User' # author association
  belongs_to :medical_record, optional: true # medical record association optional
  has_many :comments, dependent: :destroy # comments association
  has_many :noticed_events, as: :record, dependent: :destroy, class_name: 'Noticed::Event'
  has_many :notifications, through: :noticed_events, class_name: 'Noticed::Notification'

  # Counter cache for vote counts
  counter_culture :author, column_name: 'cached_votes_total'
  counter_culture :author, column_name: 'cached_votes_up', delta_column: 'cached_votes_up'
  counter_culture :author, column_name: 'cached_votes_down', delta_column: 'cached_votes_down'
  counter_culture :author, column_name: 'cached_vote_diff', delta_column: 'cached_vote_diff'

  after_create_commit :enqueue_notification_job

  scope :with_author_and_image, -> { includes(:author, image_attachment: :blob) }
  scope :with_comments_and_replies, lambda {
    includes(
      comments: [
        {
          author: {
            profile_picture_attachment: :blob
          }
        },
        {
          replies: [
            :author,
            {
              author: {
                profile_picture_attachment: :blob
              }
            }
          ]
        }
      ]
    )
  }

  scope :controversial, -> { order(cached_vote_diff: :desc) }

  private

  def enqueue_notification_job
    NewPostNotificationJob.perform_later(self)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include PostLoadable
  respond_to :html, :json

  before_action :load_post, only: %i[show edit update destroy approve disapprove]
  before_action :authorize_post, only: %i[show edit update destroy approve disapprove]

  # GET /posts or /posts.json
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:author, image_attachment: :blob)
    @posts = @q.result(distinct: true).page(params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = CommentSorter.new(@post, params[:q]).sort
    @approval_rating = @post.approval_rating
    @medical_record = @post.medical_record
    @voters_up = @post.voters_up.includes(profile_picture_attachment: :blob)
    @voters_down = @post.voters_down.includes(profile_picture_attachment: :blob)
    @new_comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
    set_medical_record
    authorize @post
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    if @post.save
      respond_with @post, location: post_url(@post), notice: 'Post was successfully created.'
    else
      respond_with @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      respond_with @post, location: post_url(@post), notice: 'Post was successfully updated.'
    else
      respond_with @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Approve (like) the current post
  def approve
    @post.liked_by current_user
    flash[:notice] = 'Post approved successfully.'
    redirect_back(fallback_location: root_path)
  end

  # Disapprove (dislike) the current post
  def disapprove
    @post.disliked_by current_user
    flash[:notice] = 'Post disapproved successfully.'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :author_id, :body, :image, :trusted, :medical_record_id)
  end

  def load_post
    @post = Post.find(params[:id])
  end

  def authorize_post
    authorize @post
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if policy(@post).new? || policy(@post).edit? && policy(@medical_record).show? %>
  <%= form_with(model: post, local: true, html: { class: 'w-full' }) do |form| %>
    <% if post.errors.any? %>
      <div class="alert alert-error">
        <label>
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        </label>
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-control w-full max-w-xs mx-auto">
      <label class="label">
        <span class="label-text">Title</span>
      </label>
      <%= form.text_field :title, placeholder: 'Type the title here', class: 'input input-bordered w-full' %>
    </div>
    <div class="form-control w-full max-w-xs mx-auto">
      <label class="label">
        <span class="label-text">Your message</span>
      </label>
      <%= form.text_area :body, placeholder: 'Type your message here', rows: 4, class: 'textarea textarea-bordered w-full' %>
    </div>
    <div class="form-control w-full max-w-xs mx-auto">
      <label class="label">
        <span class="label-text">Image</span>
      </label>
      <%= form.file_field :image, class: 'input input-bordered w-full' %>
    </div>
    <%= form.hidden_field :medical_record_id, value: @medical_record.id if @medical_record %>
    <%= form.hidden_field :author_id, value: current_user.id %>
    <div class="form-control mt-4 w-full flex justify-center">
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>
<% else %>
  <p>You are not authorized to create or edit this post.</p>
<% end %>

app/views/posts/_post.html.erb
<!-- app/views/posts/_post.html.erb -->
<div class="card bg-base-100 shadow-xl mb-4">
  <!-- Card Header -->
  <div class="card-header flex items-center space-x-4 p-4">
    <div class="avatar">
      <div class="w-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
        <% if post.author.profile_picture.attached? %>
          <%= image_tag post.author.profile_picture, alt: "#{post.author.name}'s profile picture", class: "rounded-full" %>
        <% else %>
          <img src="https://via.placeholder.com/150" alt="Default Profile Picture" class="rounded-full">
        <% end %>
      </div>
    </div>
    <h5 class="card-title text-lg font-semibold">
      <%= post.author.name %>
    </h5>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <p><%= post.body %></p>
    <% if post.image_attachment.present? %>
      <div class="p-4">
        <%= image_tag post.image_attachment, alt: "Post Image", class: "rounded-lg w-full object-cover" %>
      </div>
    <% end %>
  </div>
  <!-- Card Actions -->
  <div class="card-footer flex justify-between items-center p-4">
    <div class="flex space-x-2">
      <% if policy(post).approve? %>
        <%= button_to approve_post_path(post), method: :put, class: "btn btn-primary btn-xs" do %>
          <i class="fa-solid fa-arrow-up"></i>
        <% end %>
      <% end %>
      <% if policy(post).disapprove? %>
        <%= button_to disapprove_post_path(post), method: :put, class: "btn btn-accent btn-xs" do %>
          <i class="fa-solid fa-arrow-down"></i>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if policy(post).edit? %>
        <%= link_to edit_post_path(post), class: "btn btn-outline btn-accent btn-xs" do %>
          <i class="fa-solid fa-pencil"></i>
        <% end %>
      <% end %>
      <% if policy(post).destroy? %>
        <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline btn-accent btn-xs" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% if policy(@post).edit? %>
  <h1>Editing post</h1>
  <%= render "form", post: @post %>
  <br>
  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
<% else %>
  <p>You are not authorized to edit this post.</p>
<% end %>

app/views/posts/index.html.erb
<!-- views/post/index.html.erb -->
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold text-center mb-8">Posts</h1>
  <!-- Sorting Options -->
  <div class="flex justify-center mb-4">
    <div class="dropdown">
      <button class="btn btn-black dropdown-toggle" tabindex="0">
        Sort by <i class="fa-solid fa-caret-down" style="color: #ffffff;"></i>
      </button>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52" style="z-index: 100;">
        <li><%= link_to 'Newest', posts_path(q: { s: 'created_at desc' }), class: "dropdown-item" %></li>
        <li><%= link_to 'Oldest', posts_path(q: { s: 'created_at asc' }), class: "dropdown-item" %></li>
        <li><%= link_to 'Popularity', posts_path(q: { s: 'comments_count desc' }), class: "dropdown-item" %></li>
        <li><%= link_to 'Controversial', posts_path(q: { s: 'cached_vote_diff desc' }), class: "dropdown-item" %></li>
      </ul>
    </div>
  </div>
  <!-- Posts Display -->
  <div id="posts" class="flex flex-col justify-center gap-6">
    <% @posts.each do |post| %>
      <% if policy(post).show? %>
        <div class="card bg-gray-50 overflow-hidden shadow-sm mb-4 rounded-lg hover:bg-gray-100" style="width: 100%;">
          <!-- Card Header with Author and Updated At Date -->
          <div class="card-header flex items-center space-x-4 p-4 justify-between">
            <div class="avatar">
              <div class="w-24 rounded-full">
                <% if post.author.profile_picture? %>
                  <%= image_tag post.author.profile_picture, alt: "#{post.author.name}'s profile picture", class: "rounded-full" %>
                <% else %>
                  <img src="https://via.placeholder.com/150/000000/FFFFFF/?text=User" alt="Default Profile Picture" class="rounded-full">
                <% end %>
              </div>
            </div>
            <div class="text-right">
              <h5 class="font-mono italic text-sm">
                <%= post.updated_at.strftime("%B %d, %Y") %>
              </h5>
              <h5 class="card-title text-lg font-semibold">
                <%= link_to truncate(post.title, length: 50), post %>
              </h5>
            </div>
          </div>
          <!-- Post Content -->
          <% if post.image.attached? %>
            <div class="w-full h-48">
              <%= image_tag post.image, class: "object-cover w-full h-full" %>
            </div>
          <% end %>
          <div class="p-4">
            <p class="text-gray-600 text-center">
              <%= truncate(post.body, length: 100) %>
            </p>
            <div class="flex justify-between items-center mt-4">
              <div class="flex space-x-2">
                <%= button_to approve_post_path(post), method: :put, class: "btn btn-primary btn-xs" do %>
                  <i class="fa-solid fa-arrow-up"></i>
                <% end %>
                <%= button_to disapprove_post_path(post), method: :put, class: "btn btn-accent btn-xs" do %>
                  <i class="fa-solid fa-arrow-down"></i>
                <% end %>
              </div>
              <%= link_to "View Post", post, class: 'text-primary' %>
              <span class="text-sm text-gray-500">
                <%= post.comments.count %> <i class="fa-regular fa-comments"></i>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form', post: @post, medical_record: @medical_record %>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<!-- views/post/show.html.erb -->

<style>
  .avatar-overlap .avatar {
    margin-left: -12px;
    border: 2px solid #fff;
    border-radius: 50%;
  }

  .avatar-overlap .avatar:first-child {
    margin-left: 0;
  }
</style>
<div class="container mx-auto my-8 p-4 bg-white shadow-lg rounded-lg">
  <div class="flex justify-between items-center mb-4">
    <%= link_to posts_path, class: "btn btn-black" do %>
      <i class="fa-solid fa-circle-chevron-left" style="color: #ffffff;"></i>
    <% end %>
    <div class="text-right">
      <p class="font-mono italic text-sm">Posted <%= time_ago_in_words(@post.created_at) %> ago</p>
      <h1 class="text-2xl font-bold"><%= @post.title %></h1>
    </div>
  </div>
  <div class="post-content mb-4">
    <%= render @post %>
  </div>
  <div class="collapse collapse-arrow bg-base-400 rounded-box shadow-lg">
    <input type="checkbox" class="peer" />
    <div class="collapse-title text-xl font-medium peer-checked:bg-primary peer-checked:text-white text-center">
      Medical Record
    </div>
    <div class="collapse-content bg-white p-4 peer-checked:text-primary-content">
      <% if @medical_record.present? %>
        <%= render 'medical_records/medical_record', medical_record: @medical_record %>
      <% else %>
        <p>No medical record available.</p>
      <% end %>
    </div>
  </div>
  <div class="flex gap-4 mb-4">
    <!-- Approved By Section -->
    <div class="flex-1 bg-primary rounded-lg p-4">
      <h5 class="text-lg font-semibold text-white mb-2 text-center">Approved</h5>
      <div class="flex justify-center">
        <div class="flex -space-x-2 avatar-overlap">
          <% @voters_up.limit(4).each do |voter| %>
            <div class="tooltip" data-tip="<%= voter.name %>">
              <div class="avatar">
                <div class="w-12 h-12 rounded-full ring-2 ring-white dark:ring-gray-800">
                  <% if voter.profile_picture.present? %>
                    <%= image_tag voter.profile_picture, alt: voter.name, class: "rounded-full" %>
                  <% else %>
                    <img src="https://via.placeholder.com/150" alt="Default Profile Picture" class="rounded-full">
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <% if @voters_up.size > 4 %>
            <label for="voters-up-modal" class="avatar bg-gray-300 w-12 h-12 rounded-full flex items-center justify-center cursor-pointer ring-2 ring-white dark:ring-gray-800">
              +<%= @voters_up.size - 4 %>
            </label>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Disapproved By Section -->
    <div class="flex-1 bg-accent rounded-lg p-4">
      <h5 class="text-lg font-semibold text-white mb-2 text-center">Disapproved</h5>
      <div class="flex justify-center">
        <div class="flex -space-x-2 avatar-overlap">
          <% @voters_down.limit(4).each do |voter| %>
            <div class="tooltip" data-tip="<%= voter.name %>">
              <div class="avatar">
                <div class="w-12 h-12 rounded-full ring-2 ring-white dark:ring-gray-800">
                  <% if voter.profile_picture.present? %>
                    <%= image_tag voter.profile_picture, alt: voter.name, class: "rounded-full" %>
                  <% else %>
                    <img src="https://via.placeholder.com/150" alt="Default Profile Picture" class="rounded-full">
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <% if @voters_down.size > 4 %>
            <label for="voters-down-modal" class="avatar bg-gray-300 w-12 h-12 rounded-full flex items-center justify-center cursor-pointer ring-2 ring-white dark:ring-gray-800">
              +<%= @voters_down.size - 4 %>
            </label>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- Approval Rating Section -->
  <div class="stats shadow w-full bg-gray-100 p-4 rounded-lg mb-4 mx-auto">
    <div class="stat">
      <div class="stat-title">Approval Rating</div>
      <div class="stat-value <%= 'text-primary' if @post.approval_rating > 70 %> <%= 'text-accent' if @post.approval_rating < 50 %> <%= 'text-yellow-500' if @post.approval_rating >= 50 && @post.approval_rating <= 70 %>">
        <%= @post.approval_rating %> %
      </div>
      <div class="stat-desc">Overall Clan approval</div>
    </div>
    <div class="stat">
      <div class="stat-title">Approved</div>
      <div class="stat-value text-primary"><%= @post.get_upvotes.size %></div>
      <div class="stat-desc">Total Approvals</div>
    </div>
    <div class="stat">
      <div class="stat-title">Disapproved</div>
      <div class="stat-value text-accent"><%= @post.get_downvotes.size %></div>
      <div class="stat-desc">Total Disapprovals</div>
    </div>
    <div class="stat">
      <div class="stat-title">Total Votes</div>
      <div class="stat-value"><%= @post.get_upvotes.size + @post.get_downvotes.size %></div>
      <div class="stat-desc">All Votes</div>
    </div>
  </div>
  <!-- Modal for voters_up -->
  <input type="checkbox" id="voters-up-modal" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="font-bold text-lg">Users who approved this post</h3>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <% @post.voters_up.each do |voter| %>
              <tr>
                <td>
                  <div class="flex items-center space-x-3">
                    <div class="avatar">
                      <div class="mask mask-squircle w-12 h-12">
                        <% if voter.profile_picture.attached? %>
                          <%= image_tag(voter.profile_picture, alt: "#{voter.name} profile") %>
                        <% else %>
                          <%= image_tag("default_profile_picture.png", alt: "Default profile picture") %>
                        <% end %>
                      </div>
                    </div>
                    <div>
                      <div class="font-bold"><%= voter.name %></div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-action">
        <label for="voters-up-modal" class="btn">Close</label>
      </div>
    </div>
  </div>
  <!-- Modal for voters_down -->
  <input type="checkbox" id="voters-down-modal" class="modal-toggle" />
  <div class="modal">
    <div class="modal-box">
      <h3 class="font-bold text-lg">Users who disapproved this post</h3>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <% @post.voters_down.each do |voter| %>
              <tr>
                <td>
                  <div class="flex items-center space-x-3">
                    <div class="avatar">
                      <div class="mask mask-squircle w-12 h-12">
                        <% if voter.profile_picture.attached? %>
                          <%= image_tag(voter.profile_picture, alt: "#{voter.name} profile") %>
                        <% else %>
                          <%= image_tag("default_profile_picture.png", alt: "Default profile picture") %>
                        <% end %>
                      </div>
                    </div>
                    <div>
                      <div class="font-bold"><%= voter.name %></div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-action">
        <label for="voters-down-modal" class="btn">Close</label>
      </div>
    </div>
  </div>
  <div class="flex gap-4 mb-4">
    <!-- Comment Form Section -->
    <div class="w-full">
      <h3 class="text-xl font-bold mb-4">Leave a Comment</h3>
      <%= render partial: 'comments/form', locals: { post: @post, comment: @new_comment } %>
    </div>
  </div>
  <!-- Comment Sorting Links -->
  <div class="flex justify-center mb-4">
    <div class="dropdown">
      <button class="btn btn-black dropdown-toggle" tabindex="0">
        Sort by <i class="fa-solid fa-caret-down" style="color: #ffffff;"></i>
      </button>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52" style="z-index: 100;">
        <li> <%= link_to 'Newest', post_path(@post, q: {s: 'created_at desc'}) %> </li>
        <li> <%= link_to 'Oldest', post_path(@post, q: {s: 'created_at asc'}) %></li>
        <li> <%= link_to 'Most Popular', post_path(@post, q: {s: 'replies_count desc'}) %> </li>
        <li> <%= link_to 'Most Controversial', post_path(@post, q: {s: 'cached_vote_diff desc'}) %> </li>
      </ul>
    </div>
  </div>
  <div class="flex gap-4 mb-4">
    <!-- Comment Section -->
    <div class="w-full border border-gray-300 rounded-lg p-4">
      <ul class="timeline-vertical">
        <%= render partial: 'comments/comment', collection: @comments, as: :comment %>
      </ul>
    </div>
  </div>
</div>