config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :medical_records do
    collection do
      get 'partials/:record_type', to: 'medical_records#load_partial', as: 'load_partial'
      get 'fields_partials/:record_type', to: 'medical_records#fields_partial', as: 'fields_partial'
    end
  end

  resources :approvals

  resources :posts do
    member do
      put 'approve'
      put 'disapprove'
    end
    resources :comments, only: %i[create new show update destroy] do
      member do
        get 'edit'
        put 'approve'
        put 'disapprove'
      end
    end
  end

  resources :clans do
    resources :clan_memberships, only: %i[create destroy index show]
    member do
      get 'show_members'
      patch 'toggle_trust/:user_id', to: 'clans#toggle_trust', as: 'toggle_trust'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/views/layouts/_flash.html.erb
<!-- _flash.html.erb --><!-- _flash.html.erb -->
<% flash.each do |type, message| %>
  <div role="alert" class="<%= 'bg-blue-500' if type == 'notice' %><%= 'bg-red-500' if type == 'alert' || type == 'error' %><%= 'bg-green-500' if type == 'success' %><%= 'bg-yellow-500' if type == 'warning' %> p-4 mb-4 rounded-lg flex items-center text-white">
    <% if type == 'notice' %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <% elsif type == 'alert' || type == 'error' %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <% elsif type == 'success' %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <% elsif type == 'warning' %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>
    <% end %>
    <span><%= message %></span>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<h1>Header</h1>

app/views/layouts/_nav.html.erb
<!--views/layouts/_nav.html.erb -->
<div class="navbar bg-primary text-white">
  <div class="flex-1">
    <%= image_tag "cclogo1.png", alt: "CareClan Logo", class: "w-10" %>
    <%= link_to 'CareClan', user_signed_in? ? dashboard_path : root_path, class: "btn btn-ghost normal-case text-2xl tracking-wide font-semibold" %>
  </div>
  <div class="flex-none">
    <% if user_signed_in? %>
      <!-- Dropdown for user actions -->
      <div class="dropdown dropdown-end text-black">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <% if @user.present? && @user.profile_picture.present? %>
            <%= image_tag @user.profile_picture, alt: "User profile picture", class: "w-10 rounded-full" %>
          <% elsif current_user && current_user.profile_picture.present? %>
            <%= image_tag current_user.profile_picture, alt: "User profile picture", class: "w-10 rounded-full" %>
          <% else %>
            <%= image_tag "default_profile_picture.png", alt: "Default profile picture", class: "w-10 rounded-full" %>
          <% end %>
        </div>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-300 rounded-box w-52">
          <!-- Menu items -->
          <li><%= link_to 'Dashboard', posts_path %> </li>
          <li><%= link_to 'Medical Records', medical_records_path %></li>
          <li><%= link_to 'My Clan', clans_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: "btn" %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="emerald">
  <head>
    <meta charset="UTF-8">
    <title>CareClan - Streamline Your Family's Care</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
    <script src="https://kit.fontawesome.com/897711c116.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div>
      <% if controller_name == 'welcome' && action_name == 'index' %>
        <%= yield %>
      <% else %>
        <div>
          <% flash.each do |type, message| %>
            <%= render partial: "layouts/flash", locals: { message: message, css_class: type.to_s } %>
          <% end %>
          <%= yield %>
        </div>
      <% end %>
    </div>
  </body>
</html>